# Set a plain language title for the site.
title: Naslovnica

# Write a short description for the site. This is used for "meta description."
description: kako jednostavno izraditi web stranice uz pomoć GitHuba

# Set the language for the site. Used for "html lang." Default is English.
lang: hr

# Avoid GitHub API authentication when building locally.
github: [metadata]

# Add new template
theme: jekyll-theme-minimal
